# Generated by Django 5.2.3 on 2025-06-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('titre', models.CharField(max_length=200, unique=True, verbose_name='Titre')),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
    ]
